export enum ExpenseCategory {
  Makanan = 'makanan',
  Travel = 'travel',
  Entertainment = 'entertainment',
  Subscription = 'subscription',
  Bills = 'bills',
  Other = 'other',
}

type ExpenseCategoryKeywordMap = Record<ExpenseCategory, readonly string[]>;

export const EXPENSE_CATEGORY_KEYWORDS: ExpenseCategoryKeywordMap = {
  [ExpenseCategory.Makanan]: [
    'makan',
    'kuliner',
    'resto',
    'restoran',
    'warung',
    'kedai',
    'kantin',
    'sarapan',
    'makan siang',
    'makan malam',
    'brunch',
    'lunch',
    'dinner',
    'breakfast',
    'snack',
    'camilan',
    'jajanan',
    'kue',
    'roti',
    'bakery',
    'dessert',
    'kopi',
    'coffee',
    'cafe',
    'cafeteria',
    'teh',
    'boba',
    'minuman',
    'juice',
    'gofood',
    'grabfood',
    'shopeefood',
    'traveloka eats',
    'mcdonalds',
    'kfc',
    'burger',
    'pizza',
    'starbucks',
    'indomaret',
    'alfamart',
    'grocery',
    'groceries',
    'sembako',
    'supermarket',
    'hypermart',
    'pasar',
    'sayur',
    'buah',
    'daging',
    'ayam',
    'ikan',
  ],

  [ExpenseCategory.Travel]: [
    'travel',
    'transport',
    'transportasi',
    'perjalanan',
    'bensin',
    'bbm',
    'solar',
    'pertamina',
    'shell',
    'spbu',
    'parkir',
    'tol',
    'servis',
    'service',
    'oli',
    'ban',
    'ojek',
    'gojek',
    'grab',
    'maxim',
    'indriver',
    'gocar',
    'grabcar',
    'taxi',
    'taksi',
    'bluebird',
    'busway',
    'transjakarta',
    'mrt',
    'lrt',
    'commuter',
    'krl',
    'kereta',
    'angkot',
    'metromini',
    'bis',
    'bus',
    'pesawat',
    'tiket',
    'flight',
    'airline',
    'garuda',
    'lionair',
    'citilink',
    'kapal',
    'ferry',
    'pelni',
    'rental',
    'sewa motor',
    'sewa mobil',
  ],

  [ExpenseCategory.Entertainment]: [
    'entertainment',
    'hiburan',
    'rekreasi',
    'liburan',
    'nonton',
    'bioskop',
    'cinema',
    'cgv',
    'cinepolis',
    'xxi',
    'konser',
    'event',
    'tiket masuk',
    'game',
    'gaming',
    'steam',
    'playstation',
    'xbox',
    'nintendo',
    'mobile legend',
    'ml',
    'pubg',
    'top up',
    'diamond',
    'voucher game',
    'wisata',
    'taman',
    'museum',
    'kebun binatang',
    'waterpark',
    'gym',
    'fitness',
    'olahraga',
    'futsal',
    'badminton',
    'renang',
    'buku',
    'book',
    'gramedia',
    'majalah',
    'komik',
    'manga',
    'hobi',
    'koleksi',
  ],

  [ExpenseCategory.Subscription]: [
    'netflix',
    'disney',
    'disneyplus',
    'hbo',
    'vidio',
    'viu',
    'wetv',
    'prime video',
    'apple tv',
    'spotify',
    'youtube',
    'youtube premium',
    'apple music',
    'joox',
    'chatgpt',
    'openai',
    'claude',
    'copilot',
    'gemini',
    'midjourney',
    'canva pro',
    'notion',
    'figma',
    'adobe',
    'microsoft 365',
    'google one',
    'icloud',
    'antivirus',
    'vpn',
    'hosting',
    'domain',
    'subscription',
    'langganan',
    'berlangganan',
    'premium',
    'membership',
    'sewa',
    'renewal',
  ],

  [ExpenseCategory.Bills]: [
    'listrik',
    'pln',
    'air',
    'pdam',
    'gas',
    'lpg',
    'internet',
    'wifi',
    'indihome',
    'firstmedia',
    'biznet',
    'pulsa',
    'kuota',
    'data',
    'telkomsel',
    'xl',
    'indosat',
    'tri',
    'smartfren',
    'bill',
    'tagihan',
    'cicilan',
    'kredit',
    'angsuran',
    'kpr',
    'kartu kredit',
    'paylater',
    'kredivo',
    'akulaku',
    'shopee paylater',
    'asuransi',
    'bpjs',
    'premi',
    'pajak',
    'pbb',
    'stnk',
    'sim',
    'administrasi',
    'spp',
    'ukt',
    'kursus',
    'les',
    'sekolah',
    'kuliah',
  ],

  [ExpenseCategory.Other]: [],
};

export function inferExpenseCategory(description: string): ExpenseCategory {
  const normalizedDescription = description.toLowerCase();

  for (const [category, keywords] of Object.entries(
    EXPENSE_CATEGORY_KEYWORDS,
  ) as [ExpenseCategory, readonly string[]][]) {
    if (keywords.some((keyword) => normalizedDescription.includes(keyword))) {
      return category;
    }
  }

  return ExpenseCategory.Other;
}
